//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Defra.TradeImportsProcessor.Processor.Models.Ipaffs;


/// <summary>
/// Details of Control (Part 3)
/// </summary>
public partial class Control  //
{


    /// <summary>
    /// Feedback information of Control
    /// </summary>
    [JsonPropertyName("feedbackInformation")]
    public FeedbackInformation? FeedbackInformation { get; set; }


    /// <summary>
    /// Details on re-export
    /// </summary>
    [JsonPropertyName("detailsOnReExport")]
    public DetailsOnReExport? DetailsOnReExport { get; set; }


    /// <summary>
    /// Official inspector
    /// </summary>
    [JsonPropertyName("officialInspector")]
    public OfficialInspector? OfficialInspector { get; set; }


    /// <summary>
    /// Is the consignment leaving UK borders?
    /// </summary>
    [JsonPropertyName("consignmentLeave")]
    public ControlConsignmentLeaveEnum? ConsignmentLeave { get; set; }

}