//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Defra.TradeImportsProcessor.Processor.Models.Ipaffs;


/// <summary>
/// An organisation as part of the DEFRA system
/// </summary>
public partial class EconomicOperator  //
{


    /// <summary>
    /// The unique identifier of this organisation
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }


    /// <summary>
    /// Type of organisation
    /// </summary>
    [JsonPropertyName("type")]
    public EconomicOperatorTypeEnum? Type { get; set; }


    /// <summary>
    /// Status of organisation
    /// </summary>
    [JsonPropertyName("status")]
    public EconomicOperatorStatusEnum? Status { get; set; }


    /// <summary>
    /// Name of organisation
    /// </summary>
    [JsonPropertyName("companyName")]
    public string? CompanyName { get; set; }


    /// <summary>
    /// Individual name
    /// </summary>
    [JsonPropertyName("individualName")]
    public string? IndividualName { get; set; }


    /// <summary>
    /// Address of economic operator
    /// </summary>
    [JsonPropertyName("address")]
    public Address? Address { get; set; }


    /// <summary>
    /// Approval Number which identifies an Economic Operator unambiguously per type of organisation per country.
    /// </summary>
    [JsonPropertyName("approvalNumber")]
    public string? ApprovalNumber { get; set; }


    /// <summary>
    /// Optional Business General Number, often named Aggregation Code, which identifies an Economic Operator.
    /// </summary>
    [JsonPropertyName("otherIdentifier")]
    public string? OtherIdentifier { get; set; }


    /// <summary>
    /// Traces Id of the economic operator generated by IPAFFS
    /// </summary>
    [JsonPropertyName("tracesId")]
    public int? TracesId { get; set; }

}