//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Defra.TradeImportsProcessor.Processor.Models.Ipaffs;

public partial class IdentificationDetails  //
{


    /// <summary>
    /// Identification detail
    /// </summary>
    [JsonPropertyName("identificationDetail")]
    public string? IdentificationDetail { get; set; }


    /// <summary>
    /// Identification description
    /// </summary>
    [JsonPropertyName("identificationDescription")]
    public string? IdentificationDescription { get; set; }

}