//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Defra.TradeImportsProcessor.Processor.Models.Ipaffs;


/// <summary>
/// Impact of transport on animals
/// </summary>
public partial class ImpactOfTransportOnAnimals  //
{


    /// <summary>
    /// Number of dead animals specified by units
    /// </summary>
    [JsonPropertyName("numberOfDeadAnimals")]
    public int? NumberOfDeadAnimals { get; set; }


    /// <summary>
    /// Unit used for specifying number of dead animals (percent or units)
    /// </summary>
    [JsonPropertyName("numberOfDeadAnimalsUnit")]
    public string? NumberOfDeadAnimalsUnit { get; set; }


    /// <summary>
    /// Number of unfit animals
    /// </summary>
    [JsonPropertyName("numberOfUnfitAnimals")]
    public int? NumberOfUnfitAnimals { get; set; }


    /// <summary>
    /// Unit used for specifying number of unfit animals (percent or units)
    /// </summary>
    [JsonPropertyName("numberOfUnfitAnimalsUnit")]
    public string? NumberOfUnfitAnimalsUnit { get; set; }


    /// <summary>
    /// Number of births or abortions (unit)
    /// </summary>
    [JsonPropertyName("numberOfBirthOrAbortion")]
    public int? NumberOfBirthOrAbortion { get; set; }

}