//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System.Text.Json.Serialization;
using System.Dynamic;


namespace Defra.TradeImportsProcessor.Processor.Models.Ipaffs;


/// <summary>
/// Validation field code-message representation
/// </summary>
public partial class ValidationMessageCode  //
{


    /// <summary>
    /// Field
    /// </summary>
    [JsonPropertyName("field")]
    public string? Field { get; set; }


    /// <summary>
    /// Code
    /// </summary>
    [JsonPropertyName("code")]
    public string? Code { get; set; }

}